### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by LorenzoPane** [autocomplete-python/autocomplete-python#269]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (/Users/JoeShmo/Documents/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markRange (/Users/JoeShmo/Documents/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71)
DisplayMarkerLayer.markBufferRange (/Users/JoeShmo/Documents/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
TextEditor.markBufferRange (/Users/JoeShmo/Documents/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1753:38)
constructor._showSignatureOverlay (/Users/lorenzo/.atom/packages/autocomplete-python/lib/provider.coffee:294:23)
<unknown> (/Users/JoeShmo/.atom/packages/autocomplete-python/lib/provider.coffee:346:28)
```

**Comment by uchuugaka** [comment]
I'm seeing this too.. :(

**Comment by sadovnychyi** [comment]
Strange since I cannot see any deprecation warnings with 1.14.0-beta0.

And I also cannot see anything related to `Function.extractParams` in any of:
https://github.com/autocomplete-python/autocomplete-python/blob/master/lib/provider.coffee#L346
https://github.com/autocomplete-python/autocomplete-python/blob/master/lib/provider.coffee#L294

Maybe you could fix it and make a pull request?

**Comment by uchuugaka** [comment]
I am not running the beta, but current prod release. 
Mind you I am not highly proficient at JavaScript, but do lots of debugging in general.
What that version delta and the stack traces indicate to me is it manifests in your plugin but is not your code directly causing it, AND that it has likely been resolved at a lower layer in the frameworks/libs or app itself. I will run it later on another system with the beta version you noted. If it works there, we can say the lower level likely had the issue and resolved it. Then you might confirm with the Atom/Github team themselves and they might confirm and then you have an FAQ for nothing :)

**Comment by uchuugaka** [comment]
Specifically I'm on 1.130 x64 (macOS 10.12.1 (16B2657)) Apologies for not adding that info earlier.

**Comment by uchuugaka** [comment]
Verified 100% not your issue. 
Something lower level that gets fixed.

Thanks!
JJ

**Comment by rafarafarafarafael** [comment]
I'm getting this in Atom beta and release:

autocomplete-python (1 deprecation)
Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.
Function.extractParams - /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14
MarkerLayer.markRange - /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:215:71
DisplayMarkerLayer.markBufferRange - /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:105:52
TextEditor.markBufferRange - /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1774:38
constructor._showSignatureOverlay - /Users/rafa/.atom/packages/autocomplete-python/lib/provider.coffee:294:23
<unknown> - /Users/rafa/.atom/packages/autocomplete-python/lib/provider.coffee:346:28

**Comment by smnuman** [comment]
### 
Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.
Report Issue
Function.extractParams - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14
MarkerLayer.markRange - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:215:71
DisplayMarkerLayer.markBufferRange - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:105:52
TextEditor.markBufferRange - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1738:38
constructor._showSignatureOverlay - /Users/iArchive/.atom/packages/autocomplete-python/lib/provider.coffee:294:23
<unknown> - /Users/iArchive/.atom/packages/autocomplete-python/lib/provider.coffee:346:28

What's the problem here! I have a constant red flag in my editor!

**Comment by igorer88** [comment]
So, there's a way to fix this? u.u

**Comment by sadovnychyi** [comment]
Sorry, but as I said I cannot reproduce it thus I cannot fix it.
As @uchuugaka suggested it could be issue with something not related to this package.

**Comment by xiligey** [comment]
![11](https://cloud.githubusercontent.com/assets/17290149/24033173/8ed4c5a8-0b26-11e7-98a6-6e46a4ca4704.png)
I have the same problem.
And, when i write "import nump", it doesn't show "numpy" , can it be fixed ?

**Comment by dc-avasilev** [comment]
I have the same problem.

**Comment by billgertz** [comment]
Still getting the same deprecation notice, all packages up to date as well. What can we send to help debug?
![screen shot 2017-05-31 at 11 37 47](https://cloud.githubusercontent.com/assets/3613249/26626077/4f41e082-45f6-11e7-85b5-293ca2d298a2.png)
