### ISSUE TITLE
Specify the current project owner and relations with Kite

### ISSUE THREAD

**Issue by dessant** [autocomplete-python/autocomplete-python#308]
The main developer of this project was @sadovnychyi until recently [1], he does not appear to be a Kite employee [2].

On December 1, 2016 @dhung09, a Kite employee, made his very first pull request [3] for this project, integrating Kite. @dhung09 also had push access and merged his own PR.

On January 25, 2017 @abe33, a Kite employee, made his first pull request [4] for this project, and merged it without any public discussion taking place.

Since then @sadovnychyi gradually stopped contributing [5] and all new commits were authored by @abe33, other Kite employees are also showing activity on issue threads.

Kite is not mentioned anywhere in the README.

Please share the nature and circumstances of the apparent maintainer transition taking place, and specify how does it relate to Kite and its employees.

[1] https://github.com/autocomplete-python/autocomplete-python/graphs/contributors
[2] https://kite.com/aboutus
[3] https://github.com/autocomplete-python/autocomplete-python/pull/250
[4] https://github.com/autocomplete-python/autocomplete-python/pull/276
[5] https://github.com/autocomplete-python/autocomplete-python/commits/master?author=sadovnychyi

**Comment by sadovnychyi** [comment]
For me Kite seemed to be like an interesting *optional* integration for
python completions, so I did gave them the access since I don't have much
time implementing another completions provider by myself. It seems great –
I'm keeping the Jedi support, while Kite could work on some awesome
features from their side, so the package could constantly improve, even
when I don't have time for it. Well, it seems like it didn't go as smooth
as I expected, they did introduce some bugs and some questionable choices,
but most of bugs are already fixed.

I can assure you that I'm going to keep supporting the Jedi part of this
package, and it's not going to be replaced with Kite or something else. I'm
using it daily on my macOS machine on my daily job, and I'm still using
Jedi – and so far I'm satisfied with everything, so I didn't make any
commits to improve anything. There's a lot of bugs to be fixed, but some of
them are related to Jedi, some of them are platform specific. I'm always
open to pull requests, but I don't have time to fix all of them by myself.

README is definitely should be updated, and I hope one of @dhung09
<https://github.com/dhung09> or @abe33 <https://github.com/abe33> could do
this to reflect the things that they are doing.

**Comment by bilderbuchi** [comment]
Relevant issue: #299 #285. Also atom-minimap/minimap#588 - injecting an opt-out kite promition into the minimap plugin is in my opinion more than shady behaviour. 😞 
I don't understand at all why the Kite devs don't fork into their own `autcomplete-kite` plugin, and promote that? Especially as they plan to support more languages "soon", anyway.

**Comment by sadovnychyi** [comment]
AFAIK it's opt-in here, you *have* to choose either Jedi or Kite, cannot
say anything about minimap package.

**Comment by bilderbuchi** [comment]
sorry for being unclear, it's opt-out in the minimap plugin, and [by design](https://github.com/atom-minimap/minimap/issues/588#issuecomment-299040220) kept that way even though users all complained.

**Comment by bilderbuchi** [comment]
>  I can assure you that I'm going to keep supporting the Jedi part of this package, and it's not going to be replaced with Kite or something else. 

I'm very relieved to hear this, and that you will stay watchful, btw.

**Comment by dessant** [comment]
@sadovnychyi, thanks for following back. I'm not sure if you have researched this issue, but many of us feel the autocomplete-python package is being overtaken by the Kite team, and the popularity of this plugin is being used to promote their service.

It's also worth noting that there are no regular signs of these new maintainers being introduced to the project. Having push access before your first contribution is atypical, and it is not an isolated case of one developer.

I believe we could hear more about how this collaboration came to be, and how/where did those discussions happen.

**Comment by sadovnychyi** [comment]
@dessant, it's hard to deny that as a result they (Kite) did get a promotion out of this. It's not like we have a lot of autocomplete options available for python, so I did have some interest in Kite when it was announced. It would be awesome if Jedi (or another open source project) would add completions based on machine learning, but it didn't happen yet.

I'm sorry that they weren't properly introduced into the project (and as I said before some new bugs were created as well), but this is not a huge open source project with strict guidelines, so I considered it would be fine. (again, mistakes were made, let's learn from this and move on).

The discussion happened over the email and as I said it seemed like both parties (kite and autocomplete-python) could improve each other based on this collaboration.

There's other Atom packages (e.g. go-plus) which combines a set of features for the language, so it seems completely fine to provide multiple completion providers in this package, it's called `autocomplete-python`, not `autocomplete-jedi` or something.

This package grows, and I'm still new to this, but I'm doing my best to keep it alive.

**Comment by douglascamata** [comment]
So, one more package receiving pushes of @abe33 forcing Kite promotion. One more to uninstall. I like to keep my development environment 100% free software. 👋 

I wonder... don't Kite have its own package for Atom? Why hijack all the good open and free choices in the ecosystem?

**Comment by bilderbuchi** [comment]
In short: yes, they do; and an ill-conceived advertisement strategy (imo)

**Comment by dkerkow** [comment]
I am concerned about the way Kite devs are behaving in the atom ecosystem. I just read about the minimap incident by accident and am not comfortable with commercial services being injected into plugins like these. Why on earth is Kite enabled by default for this project? I can see your motivation for opening the plugin for other autocomplete engines, but Kite could live in a separate plugin as well while still be callable from autocomplete-python. I would strongly suggest to revert write access for Kite devs and give them the opportunity to hook in via **Opt-IN**. Everything else is harmful for the projects reputation.

**Comment by laurieskelly** [comment]
Just for context this is the screen where you make your "opt-in" choice of `Kite` or `Jedi` (a.k.a. `unnamed "lower accuracy, less complete" local engine`) during install 

![image](https://user-images.githubusercontent.com/4001044/28342719-318574fa-6bdf-11e7-9838-de569356c8db.png)

**Comment by dessant** [comment]
@sadovnychyi, how do you feel about the screenshot @laurieskelly posted? Do you believe the presentation in that promt benefits this project and its users?

**Comment by sadovnychyi** [comment]
@dessant well it states everything it does, isn't? Except that it doesn't mention that the "local" engine is powered by Jedi. Anyway, if you believe something should be done differently I'm sure there's always a solution since it's open source.

**Comment by bilderbuchi** [comment]
Yeah, along with a number of UX dark patterns to make "sure" that inexperienced users make the "right" choice (frame-highlighted vs no-frame, bright green vs grey subdued button, font weight and brightness if I see correctly). They could maybe reinforce that effect by changing the text on the horizontal line to "or, if you must insist,...". :-/
I guess nobody would object to a neutral, balanced presentation of the two options.

**Comment by adamsmith** [comment]
For added context, after the screenshot above, these are the following steps that the user must go through to get Kite:

![screen shot 2017-07-19 at 5 14 44 pm](https://user-images.githubusercontent.com/87728/28395016-dc7ac588-6ca5-11e7-8506-7c42cdcf9e86.png)

![screen shot 2017-07-19 at 5 15 05 pm](https://user-images.githubusercontent.com/87728/28395021-e0416690-6ca5-11e7-845e-1ede54d6d719.png)

(Small technicality: these screenshots say that Kite is installing but it's actually only downloading the installer binary to memory; the actual install doesn't happen unless the user goes through all three steps.  It's also worth noting that if the user clicks "Add Later" no code is sent to the Kite servers for analysis until they whitelist a directory.)

**Comment by bilderbuchi** [comment]
btw where is the code for that choice dialog? I searched for some of the strings displayed in the dialog, but couldn't find it using the github repo code search.

**Comment by Arcanemagus** [comment]
@bilderbuchi Looks like it's in this package: https://www.npmjs.com/package/kite-installer

**Comment by bilderbuchi** [comment]
hopefully @abe33 would agree to revert these changes like he [did for atom-minimap](https://github.com/atom-minimap/minimap/issues/588#issuecomment-316523163), and probably pull out kite support into a separate plugin. 
Otherwise someone else could look into identifying the Kite-related changes and propose a PR which reverts them.

**Comment by dessant** [comment]
@sadovnychyi, please tell us if you intend to revert the Kite itegration, or if we should fork the project instead.

The issue is being discussed on the from page of HN:
https://news.ycombinator.com/item?id=14836653

**Comment by franciscop** [comment]
@sadovnychyi to be fair if negative language is allowed in the choice dialogue it should also highlight the downsides of Kite:

> Uploads your files and data to internet (vulnerable, closed source, privacy disabled).

Otherwise it's just a dark pattern as many have pointed out, not just "the truth".

**Comment by DanielJoyce** [comment]
well the reviews for Kite in that article are pretty terrible from those who had used it. This doesn't look good. What marketing person thought this was a good idea?

**Comment by MrStonedOne** [comment]
I said this in the minimap thread but i'll repeat it here:

Do not spread, believe, or entertain any bullshit about forking being a form of "fragmenting the community" as a bad thing. The whole point of open source is that anybody is able to make a fork, and allow the community to decide. A fragmented community is good open source, it reduces the impacts of bad actions like this. Another name for it would be *distributed*.

The entire reason this was even a big deal was because there is no where near enough competition, there is always the "one" tool to do something. That "one" plugin that provides a function, with the runner up (if it exist) having no where near the amount of users, features, or coders.

As a user base, we have stop collesasing around these tools and start spreading out more. As it is, these open source projects become single point of failures or otherwise big targets because everybody is obsessed with using the #1 project.

So ***never*** stigmatize forking as "fragmenting the community".

**Comment by dessant** [comment]
A pull request has been submitted for removing Kite: https://github.com/autocomplete-python/autocomplete-python/pull/323.

**Comment by bilderbuchi** [comment]
Do you know why the PR submitter closed their own PR shortly after opening?

**Comment by MrStonedOne** [comment]
Its no matter, the code commiter does not have to be the pr opener.

**Comment by MrStonedOne** [comment]
#324

**Comment by faroit** [comment]
@MrStonedOne @brennv @dessant I would like a kiteless fork of project, and I am sure this will be welcomed by the community as well. Concerning the name: maybe go for `autocomplete-python-jedi`?

**Comment by bilderbuchi** [comment]
> I am sure this will be welcomed by the community as well

I wouldn't be so sure about that, because it would mean that the bullies have won, have pushed the concerned users out into an obscure package, and can keep astroturfing the established name and the known plugin with the large userbase. 

I think it would be much preferable to get #324 merged and from this day on be more vigilant about contributions. That is also what happened over at the minimap plugin afaict. Kite can still take their stuff and make an autcomplete provider for kite, and get people to use it the old-fashioned way.

**Comment by laurieskelly** [comment]
@bilderbuchi I'm not sure where I fall between your argument and @MrStonedOne. [MSO's comment](#issuecomment-317549292) has the ideological solid ground, but I also feel like maybe a more direct action would be required to fix the harm this drift from sound principles has caused. 

That all being saiiiiidddd, I don't think that Kite-removing PRs will do much good unless @sadovnychyi has revoked push access for the Kite employees who would need to approve the PR. :notes: They pretty much bought the means of production (or of auto-completion as it were), so comrades methinks the best way to re-seize them is to fork

**Comment by bilderbuchi** [comment]
Sure, but who will maintain the fork and ensure further development? I'm guessing @sadovnychyi won't be much inclined when everybody jumps ship from his fork, and it seems from the initial motivation for bringing @abe33 on board, other helpers will also be hard to find. 
Therefore, in all probability you will get to enjoy your ideological high ground, but if nobody will be prepared to pick up the dirty work (like it is right now), you will just sit on a pile of rotting code, while kite still have control of the plugin that everybody uses right now.

**Comment by brennv** [comment]
@bilderbuchi @MrStonedOne @dessant I closed #323 after I realized @janneraiskila had already done some work in this direction here back in April: https://github.com/janneraiskila/autocomplete-python-jedi/commit/9ea5de8e31c539646a245f11222e5a3840023d3b @faroit Some additional refactoring was required for the name change but the package is [out](https://atom.io/packages/autocomplete-python-jedi). This whole situation is unfortunate, and, for me anyways, somewhat unfamiliar when Python is involved.

**Comment by dessant** [comment]
@brennv, thanks for forking the project!

**Comment by dessant** [comment]
https://www.theregister.co.uk/2017/07/25/kite_flies_into_a_fork/

**Comment by dessant** [comment]
@lee-dohm, what is involved in making autocomplete-python-jedi a featured package?

https://atom.io/packages/autocomplete-python-jedi
https://github.com/brennv/autocomplete-python-jedi

**Comment by faroit** [comment]
@dessant 
 > https://www.theregister.co.uk/2017/07/25/kite_flies_into_a_fork/

"Since this story was published, autocomplete-python has been forked."

🐦: 🐦  🐦

**Comment by dessant** [comment]
> As we considered our options, we had a novel idea: buy an open source plugin, reward the author for their work, and expose new users to Kite.

> We reached out to the author of an Atom plugin called autocomplete-python. We told him about Kite, how we used machine learning to build a type inference engine that outperforms anything else out there, and we proposed forming a business relationship to work together.

https://kite.com/blog/responding-to-minimap-autocomplete-issues

The plugin being sold to Kite, or the financial nature of the collaboration, has not been disclosed by @sadovnychyi or the Kite team, not even when they were asked to do so in this thread. I think this is important to consider for everyone who decides to use this package.

**Comment by JGH1000** [comment]
Deleting minimap and autocomplete-python - will avoid Kite like fire from now on. Shoving your spyware service without user consent should not be taken lightly. 

Any advice on best autocomplete package for Python 3?

**Comment by dessant** [comment]
Kite telemetry code in Sublime package SideBarEnhancements.

https://news.ycombinator.com/item?id=14902630

**Comment by Arcanemagus** [comment]
@JGH1000 All Kite code has been removed from minimap btw.

**Comment by JGH1000** [comment]
Thanks for the link @dessant, great read.

@Arcanemagus yes, I noticed. Though this seems t be much bigger problem - as you can read in the SideBarEnhancements link, Kite gathered user data for almost a year before anyone noticed. Luckily someone noticed this in minimap, but how many other packages are affected?

We can't vet everything - @lee-dohm and other should look carefully at this as this. If this is not addressed Atom/VSCode/Sublime will become a breading ground for spyware tactics. The only thing I can think of is sandboxing with permission system and banning offenders (like Kite) from submitting anything. Otherwise the only solution would be to use very popular, well reviewed packages or move to something like JetBrains products which have most of features build in.

Sad news for anyone supporting open source software and platforms.

**Comment by jpike88** [comment]
This whole thing stinks of a startup co-opting open source projects to use them as a marketing channel.

I'm frankly disgusted by Kite's conduct here and elsewhere, and hope that you, @sadovnychyi are able to maintain a proper, open source, commercially neutral project. You do your reputation and the open source a disservice by allowing this to happen. So please fix it.

You can start by removing that ridiculous 'plan' choice, which should never have even been entertained in the first place.

But, if you sold yourself out, then make it clear to us. Stop beating around the bush and start being open to those who put their time and energy into helping your project become what it is now. Put proper Kite branding on it and make it obvious.

And to Kite, screw you guys. Seriously. Go make your own goddamn software instead of hijacking other people's creations.

**Comment by sadovnychyi** [comment]
I think those for whom it's really important should use a [fork](https://github.com/janneraiskila/autocomplete-python-jedi) instead.

As I said before, the idea of this package being backed up by a company seemed like a win-win for everybody, because it's about *adding another completion engine into autocomplete package*. I heard about Kite before they contacted me and I was excited about what they were doing, applying ML for coding is fun, give me local models (even if it's ten of GB) and I'm sold. So yeah -- I accepted their offer to integrate Kite as another provider in autocomplete-python, and we verbally agreed that I would keep working on Jedi part of it (and that it's going to be up to a user to decide what to use), while they will ship their features in. And I'm sorry, but I cannot undo that. I think there's a lot of overreaction here because of what they have done with other packages, but I don't think that it's really that out-of-context in here, and at the time when I did review their code I didn't see any way for their application to send your code somewhere automatically without you knowing about it. You have to install that thing and give your information to it, including your email, willingly. They even have an [issue](https://github.com/kiteco/kite-installer/issues/49) that it's impossible to do so without registration. 

With [this](https://github.com/kiteco/kite-installer/pull/50) merged it should look better, but people should probably demand the positioning of Kite/Jedi being randomized, or Jedi adjusted to the right for those on RTL systems, since it's still unfair. But that's up to community! I can fix bugs and answer on issues sometimes, but this thread and the whole story is getting really hard to follow. I didn't have any communication with Kite guys ~since I gained the push access to them, so you should probably send any demands related to Kite to them instead of me, I *cannot* just remove them.

**Comment by dessant** [comment]
> As I said before, the idea of this package being backed up by a company seemed like a win-win for everybody

No @sadovnychyi, you did not say autocomplete-python is sponsored or owned by Kite. This was your initial explanation for integrating Kite:

> For me Kite seemed to be like an interesting *optional* integration for python completions, so I did gave them the access since I don't have much time implementing another completions provider by myself.

And that was the narrative until the issue received widespread attention, despite repeated calls everywhere to clarify why are Kite employees acting like they own this project, and why isn't there any resistance from your part.

When you are paid to endorse a product, the first thing to disclose is that you are being paid for it, the fact that you find the product interesting is secondary.

We have trusted you as the owner of a FOSS project, and by refusing to disclose that the package was sold, you have deceived us and robbed us from the opportunity to look into who the new owners are, to decide if we should also trust *them*, and whether it is still safe to continue using the project.

Please don't insult your users by twisting reality.

The README and package description still does not mention who the new owners of autocomplete-python are.

**Comment by DanielJoyce** [comment]
Its also not clear that the Kite plugin UPLOADS potentially proprietary code to the cloud for analysis. That's the biggest red flag, and it should be in BIG RED LETTERS because it impacts everyone who uses this program for internal development.

**Comment by MrStonedOne** [comment]
>As I said before, the idea of this package being backed up by a company seemed like a win-win for everybody, because it's about adding another completion engine into autocomplete package. 

Ya, and now you see how horribly competition works when you give certain entities the ability to dictate the terms, as well as the power to just flat out control how they and their competition are represented. It breeds bad faith and dark UI patterns.

This very quickly, in the course of a few commits, went from competing prediction engines to the engine that has a financial motivation abusing their control over this repo to trick more users into signing up.

It doesn't matter if you are offering a free service, if you have a scaling percentage of paid conversions, more free users == more paid users, and giving them control over what is suppose to be a neutral ground is a conflict of interest.

Kit employees commiting to this repo can not act in the best interest of this plugin or its users because they also have a conflicting interest in promoting the company's products, regardless of how it effects the plugin or its users.

And it doesn't matter how much those employees convince themselves they are neutral or that they are acting in the best interest of this plugin and its users, the whole point of worrying over CoI's is preventing even a subconscious bias.

So, at this juncture, there are two options:

* Either this becomes the Official™ Kite™ auto complete plugin.

OR

* Kite™ and their employees are removed from this repo to keep it neutral.

Those are it, those are the two choices. There is no neutral third option, there is no middle ground. 

You can not have a neutral market of competition when one side has both financial motivators and control over the market (this plugin).

**Comment by jpike88** [comment]
> As I said before, the idea of this package being backed up by a company seemed like a win-win for everybody

No, it's not a win-win. It's a win-lose. The losers are those who worked with an open source project, and expect it to continue respect the principles of being open source. And that is transparency.

So as @MrStonedOne said, you either declare that this 

>So yeah -- I accepted their offer to integrate Kite as another provider in autocomplete-python
>you should probably send any demands related to Kite to them instead of me, I cannot just remove them.

So it's not just an offer to integrate something, they basically bought you. You have lost control of your repo, and it is at least in part the property of Kite.

So brand it as a Kite product (or a co-owned Kite and @sadovnychyi product), and make it clear to developers that this open source project is *not* what it used to be, and any future improvements (or even this repo being made private in future) is done at the whims of Kite.

Simple stuff. We all deserve your honesty, and if Kite has that level of control over you where you can't even do the right thing, then what the hell kind of agreement did you enter into!

**Comment by JGH1000** [comment]
After reading @sadovnychyi comments it is clear that further discussion on those issues should be done with Atom devs and the community. Probably worth opening a ticket to find a solution to this very big challenge to open source community.

@sadovnychyi - I agree with other that you should add much more information regarding any compensation you might have received from Kite and clarify to user that the Kite company co-owns the plugin and that activating it means the code will be send to them (which might not be secure). Also claiming that Kite is better than Jedi should be backed up by 3rd party reviews - novice users might be swayed by the description not realizing the underlying issues. 

This is no longer an open-source, transparent product as we have no idea what this company would do with the code (especially given their very immoral tactics). People should think twice about using their services.

For anyone that cares, we should all move to autocomplete-python-jedi which is kindly supported by @brennv. He seems to be making a lot of changes to it as well. Spread the word.

**Comment by faroit** [comment]
> For anyone that cares, we should all move to autocomplete-python-jedi which is kindly supported by @brennv. He seems to be making a lot of changes to it as well. Spread the word.

https://twitter.com/pycoders/status/893473358922358784

**Comment by ghisvail** [comment]
As a result of this thread, I have now replaced this plugin with `autocomplete-python-jedi` and will be actively recommending others to follow this move.

**Comment by JGH1000** [comment]
Update to anyone interested - in the next release, Atom will introduce the IDE functionality. It has autocomplete, linting, refactoring, formatting and everything you could want. Nteract member @lgeiger already create an early access package called ide-python that wraps the python language server developed by Palantir (@gatesn and others). Clearly the way to go for python-related development (faster and much more feature packed) and having a single package reduces a chance of rouge code. Can't wait for a stable release, exciting times!

https://github.com/lgeiger/ide-python
https://github.com/palantir/python-language-server

**Comment by bilderbuchi** [comment]
I'm not yet sure how I feel about Facebook's bsd+patents license that is used in atom-ide-ui, and the resource usage of all that extra stuff.

**Comment by brennv** [comment]
@bilderbuchi Breaking news http://www.zdnet.com/article/facebook-relicenses-react-in-the-face-of-open-source-dev-backlash/

**Comment by bilderbuchi** [comment]
Well, that's for react and a good development, but atom-ide-ui still has the patents file as of now: https://github.com/facebook-atom/atom-ide-ui?files=1

**Comment by DanAlexson90** [comment]
> For anyone that cares, we should all move to autocomplete-python-jedi which is kindly supported by @brennv. He seems to be making a lot of changes to it as well. Spread the word.

Is it still supported by @brennv ?

**Comment by sanzaypant** [comment]
It's also worth noting that current Github chief  is also one of the investors in this company.
